variables:
  DOCKER_DRIVER: overlay
services:
    - labreg.arvancloud.com:5000/docker:dind
before_script:
    - ls
    - pwd
    - export GOPATH=/root/go
    - export PATH=$PATH:/opt/go/bin
    - mkdir -p $GOPATH/src/arvancloud/
    - ln -sf `pwd` $GOPATH/src/arvancloud/redins

stages:
    - test
    - deploy

test:
    stage: test
    image: labreg.arvancloud.com:5000/shared_runner:latest
    script:
        - echo test
        - redis-server &
        - cd $GOPATH/src/arvancloud/redins
        - go get
        - go build
        - go test ./...
    artifacts:
        paths:
        - ./redins
    only:
        - dev

deploy:
    stage: deploy
    image: labreg.arvancloud.com:5000/docker:latest
    dependencies:
    - test
    script:
        - echo deploy
        - BUILD_VERSION=`cat VERSION`-$CI_JOB_ID
        - docker login labreg.arvancloud.com:5000 -u labreg -p 123123
        - docker build . -t labreg.arvancloud.com:5000/arvan_redins:$BUILD_VERSION
        - docker push labreg.arvancloud.com:5000/arvan_redins:$BUILD_VERSION
    only:
        - dev
