services:
    - docker:dind

before_script:
    - ls
    - pwd
    - export GOPATH=/root/go
    - export PATH=$PATH:/opt/go/bin
    - mkdir -p $GOPATH/src/arvancloud/
    - ln -sf `pwd` $GOPATH/src/arvancloud/redins
    - redis-server &

stages:
    - test
    - deploy

test:
    stage: test
    script:
        - echo test
        - cd $GOPATH/src/arvancloud/redins
        - go get
        - go build
        - go test ./...
    artifacts:
        paths:
        - ./redins
    only:
        - dev

deploy:
    stage: deploy
    dependencies:
    - test
    script:
        - echo deploy
        - docker build . -t labreg.arvancloud.com:5000/arvan_redins:0.1.3
        - docker push labreg.arvancloud.com:5000/arvan_redins:0.1.3
    only:
        - dev
